# Generated by Django 3.0.6 on 2020-05-11 08:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('club_account_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=12)),
                ('agent', models.CharField(choices=[(1, 'Agent'), (0, 'Player')], default='0', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=3)),
                ('club_id', models.IntegerField()),
                ('chip_value', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('platform', models.CharField(choices=[('UP', 'Upoker'), ('PB', 'PokerBros'), ('PPP', 'PPPoker'), ('ANP', 'All New Poker'), ('PT', 'PokerTime')], default='PB', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rakeback_percentage', models.DecimalField(decimal_places=3, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('chip_value', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('agent_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='agents.AgentPlayer')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_deals', to='agents.Club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='agent_players',
            field=models.ManyToManyField(related_name='clubs', through='agents.Deal', to='agents.AgentPlayer'),
        ),
        migrations.CreateModel(
            name='AccountClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rakeback_percentage', models.DecimalField(decimal_places=3, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('chip_value', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_deal', to='agents.Account')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_deal', to='agents.Club')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='agent_player',
            field=models.ManyToManyField(related_name='accounts', to='agents.AgentPlayer'),
        ),
        migrations.AddField(
            model_name='account',
            name='clubs',
            field=models.ManyToManyField(related_name='accounts', through='agents.AccountClub', to='agents.Club'),
        ),
    ]
