# Generated by Django 3.0.6 on 2020-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentplayer',
            name='agent',
            field=models.IntegerField(choices=[('AG', 'Agent'), ('PLY', 'Player')], default=0),
        ),
    ]
