# Generated by Django 3.0.6 on 2020-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_auto_20200522_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentplayer',
            name='code',
            field=models.CharField(max_length=12),
        ),
    ]
