# Generated by Django 3.0.6 on 2020-05-24 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0016_auto_20200523_2345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('user', 'club', 'referral_id')},
        ),
    ]
