# Generated by Django 3.0.6 on 2020-05-28 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_agent_player'),
        ('agents', '0020_auto_20200528_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentplayer',
            name='note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
    ]
