# Generated by Django 3.0.6 on 2020-05-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_agentplayer_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentplayer',
            old_name='note',
            new_name='notes',
        ),
    ]
