# Generated by Django 3.0.6 on 2020-05-07 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=3)),
                ('chip_value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('platform', models.CharField(choices=[('UP', 'Upoker'), ('PB', 'PokerBros'), ('PPP', 'PPPoker')], default='PB', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('club_agent_id', models.IntegerField()),
                ('rakeback', models.DecimalField(decimal_places=3, max_digits=3)),
                ('club', models.ManyToManyField(related_name='agents', to='agents.Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('club_account_id', models.IntegerField()),
                ('rakeback', models.DecimalField(decimal_places=3, max_digits=3)),
                ('agent', models.ManyToManyField(related_name='accounts', to='agents.Agent')),
                ('club', models.ManyToManyField(blank=True, related_name='accounts', to='agents.Club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='agents.Player')),
            ],
        ),
    ]
