# Generated by Django 3.0.6 on 2020-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='platform',
            field=models.CharField(choices=[('UP', 'Upoker'), ('PB', 'PokerBros'), ('PPP', 'PPPoker')], default='PB', max_length=3),
        ),
    ]
