# Generated by Django 3.0.6 on 2020-05-08 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='club',
        ),
        migrations.AddField(
            model_name='agent',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agents.Club'),
            preserve_default=False,
        ),
    ]
