# Generated by Django 3.0.6 on 2020-05-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200508_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_id',
            field=models.IntegerField(default=121212),
            preserve_default=False,
        ),
    ]
