# Generated by Django 3.0.6 on 2020-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200511_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentplayer',
            name='agent',
            field=models.IntegerField(choices=[(1, 'Agent'), (0, 'Player')], default=0),
        ),
    ]
