# Generated by Django 3.0.6 on 2020-05-10 21:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting_engine', '0002_remove_agentreport_agent'),
        ('agents', '0003_club_club_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rakeback_percentage', models.DecimalField(decimal_places=3, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('chip_value', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
        migrations.CreateModel(
            name='AgentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rakeback_percentage', models.DecimalField(decimal_places=3, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('chip_value', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('agent_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='agents.AgentPlayer')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='account',
            name='club',
        ),
        migrations.RemoveField(
            model_name='account',
            name='player',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rakeback',
        ),
        migrations.AlterField(
            model_name='club',
            name='chip_value',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='club',
            name='platform',
            field=models.CharField(choices=[('UP', 'Upoker'), ('PB', 'PokerBros'), ('PPP', 'PPPoker'), ('ANP', 'All New Poker'), ('PT', 'PokerTime')], default='PB', max_length=3),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='deal',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_deals', to='agents.Club'),
        ),
        migrations.AddField(
            model_name='accountclub',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_rakeback', to='agents.Account'),
        ),
        migrations.AddField(
            model_name='accountclub',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_rakeback', to='agents.Club'),
        ),
        migrations.AddField(
            model_name='account',
            name='agent_player',
            field=models.ManyToManyField(related_name='accounts', to='agents.AgentPlayer'),
        ),
        migrations.AddField(
            model_name='club',
            name='agent_players',
            field=models.ManyToManyField(related_name='clubs', through='agents.Deal', to='agents.AgentPlayer'),
        ),
    ]
