# Generated by Django 3.0.6 on 2020-05-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20200506_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='agent',
            field=models.ManyToManyField(related_name='accounts', to='agents.Agent'),
        ),
    ]
