# Generated by Django 3.0.6 on 2020-05-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20200510_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountclub',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='agents.Account'),
        ),
        migrations.AlterField(
            model_name='accountclub',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='agents.Club'),
        ),
    ]
