# Generated by Django 3.0.6 on 2020-05-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_account_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rakeback',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
            preserve_default=False,
        ),
    ]
