# Generated by Django 3.0.6 on 2020-05-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20200510_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clubs',
            field=models.ManyToManyField(related_name='accounts', through='agents.AccountClub', to='agents.Club'),
        ),
        migrations.AlterField(
            model_name='accountclub',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_deal', to='agents.Account'),
        ),
        migrations.AlterField(
            model_name='accountclub',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deal', to='agents.Club'),
        ),
    ]
