# Generated by Django 3.0.6 on 2020-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_auto_20200514_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='agent_players',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='agents.AgentPlayer'),
        ),
        migrations.AlterField(
            model_name='account',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='accounts', through='agents.AccountClub', to='agents.Club'),
        ),
    ]
