# Generated by Django 3.0.6 on 2020-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20200516_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentplayer',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('agent_player', 'club')},
        ),
    ]
