# Generated by Django 3.0.6 on 2020-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_auto_20200519_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='club_account_id',
            field=models.IntegerField(unique=True),
        ),
    ]
