# Generated by Django 3.0.6 on 2020-05-21 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0010_auto_20200520_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='agent_players',
        ),
        migrations.RemoveField(
            model_name='club',
            name='chip_value',
        ),
        migrations.AddField(
            model_name='club',
            name='users',
            field=models.ManyToManyField(related_name='clubs', through='agents.Deal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('user', 'club')},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='agent_player',
        ),
    ]
