# Generated by Django 3.0.6 on 2020-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_auto_20200521_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='referral_id',
            field=models.IntegerField(blank=True, default=43333),
            preserve_default=False,
        ),
    ]
