# Generated by Django 3.0.6 on 2020-05-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_deal_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='referral_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
