# Generated by Django 3.0.6 on 2020-05-22 07:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0014_auto_20200522_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentplayer',
            unique_together={('code', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together={('code', 'platform')},
        ),
    ]
