# Generated by Django 3.0.6 on 2020-05-28 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0004_remove_note_agent_player'),
        ('agents', '0020_auto_20200528_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet', to='agents.Deal')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debits', to='balance.BalanceSheet')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='balance.BalanceSheet')),
            ],
        ),
    ]
