# Generated by Django 3.0.6 on 2020-05-28 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_auto_20200528_1239'),
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='agent_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet', to='agents.AgentPlayer'),
        ),
    ]
