# Generated by Django 3.0.6 on 2020-05-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_balancesheet_agent_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='note',
            new_name='notes',
        ),
    ]
