# Generated by Django 3.0.6 on 2020-05-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_auto_20200514_2202'),
        ('accounting_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_winloss', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_rake', models.DecimalField(decimal_places=2, max_digits=7)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('jackpot', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('hands', models.IntegerField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='agents.Account')),
                ('agent_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='agents.AgentPlayer')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='agents.Club')),
            ],
        ),
        migrations.DeleteModel(
            name='AccountReport',
        ),
    ]
