# Generated by Django 3.0.6 on 2020-05-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_auto_20200514_2202'),
        ('accounting_engine', '0002_auto_20200515_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='agents.Account'),
        ),
        migrations.AlterField(
            model_name='report',
            name='agent_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='agents.AgentPlayer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='agents.Club'),
        ),
    ]
