# Generated by Django 3.0.6 on 2020-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_engine', '0005_auto_20200516_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hands',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='insurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='jackpot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
