# Generated by Django 3.0.6 on 2020-05-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20200510_2108'),
        ('accounting_engine', '0002_remove_agentreport_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreport',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='agents.AgentPlayer'),
        ),
        migrations.DeleteModel(
            name='AgentReport',
        ),
    ]
